#Mise à jour automatique du fichier src/polysio.properties
#Fri Apr 10 17:01:21 CEST 2026
/**=Adresse Fichiers Assest **/
db.utilisateur=
game.maxPlayers=6
game.startingMoney=1500
langue=fr
musique=on
pf.case0=/asset/Plateau/Case/0.png
pf.case1=/asset/Plateau/Case/1.png
pf.case10=/asset/Plateau/Case/10.png
pf.case11=/asset/Plateau/Case/11.png
pf.case12=/asset/Plateau/Case/12.png
pf.case13=/asset/Plateau/Case/13.png
pf.case14=/asset/Plateau/Case/14.png
pf.case15=/asset/Plateau/Case/15.png
pf.case16=/asset/Plateau/Case/16.png
pf.case17=/asset/Plateau/Case/17.png
pf.case18=/asset/Plateau/Case/18.png
pf.case19=/asset/Plateau/Case/19.png
pf.case2=/asset/Plateau/Case/2.png
pf.case20=/asset/Plateau/Case/20.png
pf.case21=/asset/Plateau/Case/21.png
pf.case22=/asset/Plateau/Case/22.png
pf.case23=/asset/Plateau/Case/23.png
pf.case24=/asset/Plateau/Case/24.png
pf.case25=/asset/Plateau/Case/25.png
pf.case26=/asset/Plateau/Case/26.png
pf.case27=/asset/Plateau/Case/27.png
pf.case28=/asset/Plateau/Case/28.png
pf.case29=/asset/Plateau/Case/29.png
pf.case3=/asset/Plateau/Case/3.png
pf.case30=/asset/Plateau/Case/30.png
pf.case31=/asset/Plateau/Case/31.png
pf.case32=/asset/Plateau/Case/32.png
pf.case33=/asset/Plateau/Case/33.png
pf.case34=/asset/Plateau/Case/34.png
pf.case35=/asset/Plateau/Case/35.png
pf.case36=/asset/Plateau/Case/36.png
pf.case37=/asset/Plateau/Case/37.png
pf.case38=/asset/Plateau/Case/38.png
pf.case39=/asset/Plateau/Case/39.png
pf.case4=/asset/Plateau/Case/4.png
pf.case40=/asset/Plateau/Case/40.png
pf.case5=/asset/Plateau/Case/5.png
pf.case6=/asset/Plateau/Case/6.png
pf.case7=/asset/Plateau/Case/7.png
pf.case8=/asset/Plateau/Case/8.png
pf.case9=/asset/Plateau/Case/9.png
pf.case99=/asset/Plateau/Case/centre.png
