#Mise à jour automatique du fichier src/polysio.properties
<<<<<<< HEAD
#Thu Mar 05 09:14:50 CET 2026
=======
#Thu Mar 05 09:04:02 CET 2026
>>>>>>> lucas2
db.utilisateur=
game.maxPlayers=6
game.startingMoney=1500
langue=fr
musique=on
